name: Copy static files
description: "Copy schematics, pinouts and 3D models from content/hardware to static/resources"
runs:
  using: composite
  steps:
    - name: Copy Static Files
      shell: bash
      run: |
        mkdir -p static/resources/schematics static/resources/pinouts static/resources/models
        find ./content/hardware -type f -name "*-schematics.pdf" -exec cp {} ./static/resources/schematics/ \;
        find ./content/hardware -type f -name "*-full-pinout.pdf" -exec cp {} ./static/resources/pinouts/ \;
        find ./content/hardware -type f -name "*-pinout.png" -exec cp {} ./static/resources/pinouts/ \;
        find ./content/hardware -type f -name "*-step.zip" -exec cp {} ./static/resources/models/ \;
