name: Validate Content

on:
  repository_dispatch:
    types: deploy
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

permissions:
  contents: read

jobs:
  spell_check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run spell check
        run: |
          pip install codespell==2.3.0
          codespell -I "scripts/resources/spell-check-ignore-list.txt" --skip="*.svg,*.dxf,*.pdf,./content/hardware/02.uno/boards/uno-q/datasheet/datasheet.md" ./content/

  lint:
    name: Content Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14]

    steps:
      - uses: actions/checkout@v4

      - name: Run linter
        run: |
          cd scripts/validation
          ./content-lint.sh -p '../../content/hardware/'

  validate_app_lab_markdown:
    name: App Lab - Validate Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Validate Markdown
        run: npx markdownlint-cli "content/software/app-lab/**/*.md" --config "content/software/app-lab/.markdownlint.yaml" --ignore-path "content/software/app-lab/.markdownlintignore"

  validate_app_lab_links:
    name: App Lab - Validate Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Validate Links
        run: python3 scripts/validation/relative_links/relative_links.py validate content/software/app-lab

  validate_app_lab_images:
    name: App Lab - Validate Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Validate Images
        run: python3 scripts/validation/image_links/image_links.py validate content/software/app-lab
